# General configuration
# -----------------------------------------------------------------------------
#
nameOverride: ''
fullnameOverride: ''
global: {}

# Deployment resource
# -----------------------------------------------------------------------------
#
replicas: 1
extraEnv: []
image:
  repository: quay.io/2i2c/k8s-node-operator
  tag: 0.0.1-0.dev.git.13.hdd314ba
resources: {}
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534 # nobody user
  runAsGroup: 65534 # nobody group

podSecurityContext: {}
podAnnotations: {}
nodeSelector: {}
affinity: {}
tolerations: []

# Service resource
# -----------------------------------------------------------------------------
#
service:
  type: ClusterIP
  port: 80

# ServiceAccount resource
# -----------------------------------------------------------------------------
#
serviceAccount:
  create: true
  name: ''
  annotations: {}