apiVersion: v2
name: jupyterhub-node-warmer
description: A Helm chart for deploying the jupyterhub-node-warmer service on Zero to JupyterHub clusters.
type: application
version: 0.0.1-set.by.chartpress
appVersion: "0.1.0"
